import { SHOT_DEFINITIONS } from '../../systems/player-shots/ShotDefinitions.js';

export const PLAYER_CONFIGS = {
  reimu: {
    id: 'reimu',
    displayName: '博麗靈夢',
    title: '樂園的巫女',
    description: '均衡移動與穩定雙發，適合初次挑戰。',
    color: 0xdd2222,
    accentColor: 0xffe8b0,
    speedNormal: 260,
    speedFocus: 130,
    hitboxRadius: 3,
    grazeRadius: 20,
    shipRadius: 14,
    shot: SHOT_DEFINITIONS.reimu,
  },
  marisa: {
    id: 'marisa',
    displayName: '霧雨魔理沙',
    title: '普通的魔法使',
    description: '高速移動與集中火力，容錯較低但擊破更快。',
    color: 0x222233,
    accentColor: 0xfff066,
    speedNormal: 305,
    speedFocus: 145,
    hitboxRadius: 3,
    grazeRadius: 20,
    shipRadius: 14,
    shot: SHOT_DEFINITIONS.marisa,
  },
  flandre: {
    id: 'flandre',
    displayName: '芙蘭朵露',
    title: '惡魔之妹',
    description: '慢速高爆發與扇形彈道，近距離壓制能力強。',
    portraitKey: 'portrait-flandre',
    portraitPath: 'assets/characters/flandre.png',
    color: 0x7b1836,
    accentColor: 0xffcc55,
    speedNormal: 245,
    speedFocus: 115,
    hitboxRadius: 3,
    grazeRadius: 20,
    shipRadius: 14,
    shot: SHOT_DEFINITIONS.flandre,
  },
};
